### ISSUE TITLE
Unable to run on Mac using java 1.8.0_202

### ISSUE THREAD

**Issue by somerboy** [pegasystems/pega-tracerviewer#10]
I recently upgraded computers and Java got upgraded from 1.5 to 1.8. When I run the command "java -Xms512M -Xmx1G -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -jar pega-tracerviewer-3.0.jar" I get a null pointer exception immediately. 

021-08-13 09:14:10,361 [INFO ] [                          main] (            com.pega.gcs.tracerviewer.TracerViewer) - Default Locale: en_US args length: 0
2021-08-13 09:14:11,990 [ERROR] [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) - TracerViewer error reading command line arguments.
java.lang.NullPointerException: null
	at java.awt.Window.init(Window.java:497) ~[?:1.8.0_202]
	at java.awt.Window.<init>(Window.java:537) ~[?:1.8.0_202]
	at java.awt.Frame.<init>(Frame.java:420) ~[?:1.8.0_202]
	at java.awt.Frame.<init>(Frame.java:385) ~[?:1.8.0_202]
	at javax.swing.JFrame.<init>(JFrame.java:189) ~[?:1.8.0_202]
	at com.pega.gcs.fringecommon.guiutilities.BaseFrame.<init>(BaseFrame.java:61) ~[fringeutils-common-3.0.jar:?]
	at com.pega.gcs.tracerviewer.TracerViewer.<init>(TracerViewer.java:72) ~[pega-tracerviewer-3.0.jar:?]
	at com.pega.gcs.tracerviewer.TracerViewer$6.run(TracerViewer.java:548) [pega-tracerviewer-3.0.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_202]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_202]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_202]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_202]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_202]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_202]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_202]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_202]

**Comment by vargm** [comment]
Hi, Can you try using the v3.3.0 from the [releases](https://github.com/pegasystems/pega-tracerviewer/releases).
let me know if that helps/works.
Thanks

**Comment by bmck2006** [comment]
I had similar issue. I fixed by updating the line 48 in the pega-tracerviewer unix script file to:
`# Add default JVM options here. You can also use JAVA_OPTS and PEGA_TRACERVIEWER_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Duser.dir=$APP_HOME" "-Dfile.encoding=UTF-8" "-Xms512M" "-Xmx1G" "-XX:+UseG1GC" "-XX:+UseConcMarkSweepGC" "-XX:+IgnoreUnrecognizedVMOptions"'`

To fix:
Unrecognized VM option 'UseParNewGC'
https://stackoverflow.com/questions/49962437/unrecognized-vm-option-useparnewgc-error-could-not-create-the-java-virtual

To fix:
Unrecognized VM option 'UseConcMarkSweepGC'
https://stackoverflow.com/questions/65546614/unrecognized-vm-option-useconcmarksweepgc-when-running-sample-project

With the above code change, TracerViewer is running fine for me in Mac

java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
