### ISSUE TITLE
Tracerviewer 3.4.1 - Error "UTF-8 has occurred while loading" when opening trace file.

### ISSUE THREAD

**Issue by dvmierlo** [pegasystems/pega-tracerviewer#11]
When using Tracerviewer version 3.4.0 and 3.4.1, I see an error "UTF-8 has occurred while loading". Tracerviewer version 3.3 can open the same trace file without any issues.

![pega-tracerviewer-3 4-load-error](https://user-images.githubusercontent.com/1241179/155492348-e805bd85-4155-4cfa-a02d-433a848c15ec.jpg)

I have attached the generated Tracerviewer logs of version 3.3 and 3.4.1 when opening the tracefile.

**Log tracerviewer version 3.3**
2022-02-24 09:42:52,896 [                          main] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Default Locale: en_US args length: 1
2022-02-24 09:42:52,996 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Non option arg element: %*

2022-02-24 09:42:53,043 [              AWT-EventQueue-0] (  com.pega.gcs.fringecommon.guiutilities.BaseFrame) [INFO ] - Using LAF class: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
2022-02-24 09:42:53,059 [              AWT-EventQueue-0] (  com.pega.gcs.fringecommon.guiutilities.BaseFrame) [INFO ] - Loading Plugins - user.dir: C:\Users\__USER_FOLDER__\pega-tracerviewer-3.3-log4j-2.17 pluginsUrl: <NULL>
2022-02-24 09:42:54,438 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - TracerViewer - Started
2022-02-24 09:42:54,480 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Processing file: %*
2022-02-24 09:42:54,498 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - "%*" is not a file.
2022-02-24 09:43:29,372 [   SwingWorker-pool-3-thread-1] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [INFO ] - TracerFileLoadTask - Using Charset: UTF-8
2022-02-24 09:43:29,372 [   SwingWorker-pool-3-thread-1] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [INFO ] - TracerFileLoadTask - Loading file: C:\Users\__USER_FOLDER__\Temp\Trace-GenerateID-Pega8.xml
2022-02-24 09:43:29,441 [                      Thread-4] (ega.gcs.fringecommon.guiutilities.FileReaderThread) [INFO ] - FileReaderThread - Read 292820 bytes in 1 secs. Total Read=292820 Read Speed=286,0 KB/secs
2022-02-24 09:43:29,457 [                      Thread-4] (ega.gcs.fringecommon.guiutilities.FileReaderThread) [INFO ] - FileReaderThread - finished tailing.
2022-02-24 09:43:30,084 [   SwingWorker-pool-3-thread-1] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [INFO ] - startSeek is -1. exiting..
2022-02-24 09:43:30,104 [   SwingWorker-pool-3-thread-1] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [INFO ] - Processed 228 trace events in 1 secs Average: 366.0 FileReadByteArray blocks: 2
2022-02-24 09:43:30,401 [              AWT-EventQueue-0] (.gcs.fringecommon.guiutilities.RecentFileContainer) [INFO ] - Updated recent file property: bookmark [com.pega.gcs.fringecommon.guiutilities.bookmark.BookmarkContainer@2ef42671]
2022-02-24 09:43:30,417 [              AWT-EventQueue-0] (     com.pega.gcs.tracerviewer.TracerDataMainPanel) [INFO ] - updateDisplayPanel
2022-02-24 09:43:30,417 [              AWT-EventQueue-0] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [INFO ] - TracerFileLoadTask - Done: C:\Users\__USER_FOLDER__\Temp\Trace-GenerateID-Pega8.xml processedCount:228
2022-02-24 09:43:37,317 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - TracerViewerSetting ByteSize: 52
2022-02-24 09:43:37,332 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Open File List ByteSize: 44
2022-02-24 09:43:37,332 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - TracerViewer - Stopped

**Log tracerviewer version 3.4.1**
2022-02-24 09:44:05,179 [                          main] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Default Locale: en_US args length: 1
2022-02-24 09:44:05,310 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Non option arg element: %*

2022-02-24 09:44:05,357 [              AWT-EventQueue-0] (  com.pega.gcs.fringecommon.guiutilities.BaseFrame) [INFO ] - Using LAF class: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
2022-02-24 09:44:06,877 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - TracerViewer - Started
2022-02-24 09:44:06,877 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - Processing file: %*
2022-02-24 09:44:06,877 [              AWT-EventQueue-0] (            com.pega.gcs.tracerviewer.TracerViewer) [INFO ] - "%*" is not a file.
2022-02-24 09:44:19,898 [              AWT-EventQueue-0] (      com.pega.gcs.tracerviewer.TracerFileLoadTask) [ERROR] - Execution Error during TracerFileLoadTask
java.util.concurrent.ExecutionException: java.nio.charset.IllegalCharsetNameException: UTF-8
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_321]
	at javax.swing.SwingWorker.get(Unknown Source) ~[?:1.8.0_321]
	at com.pega.gcs.tracerviewer.TracerFileLoadTask.completeLoad(TracerFileLoadTask.java:399) [pega-tracerviewer-3.4.1.jar:3.4.1]
	at com.pega.gcs.tracerviewer.TracerFileLoadTask.done(TracerFileLoadTask.java:381) [pega-tracerviewer-3.4.1.jar:3.4.1]
	at javax.swing.SwingWorker$5.run(Unknown Source) [?:1.8.0_321]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source) [?:1.8.0_321]
	at sun.swing.AccumulativeRunnable.run(Unknown Source) [?:1.8.0_321]
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source) [?:1.8.0_321]
	at javax.swing.Timer.fireActionPerformed(Unknown Source) [?:1.8.0_321]
	at javax.swing.Timer$DoPostEvent.run(Unknown Source) [?:1.8.0_321]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_321]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_321]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_321]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_321]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_321]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_321]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_321]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.nio.charset.IllegalCharsetNameException: UTF-8
	at java.nio.charset.Charset.checkName(Unknown Source) ~[?:1.8.0_321]
	at java.nio.charset.Charset.lookup2(Unknown Source) ~[?:1.8.0_321]
	at java.nio.charset.Charset.lookup(Unknown Source) ~[?:1.8.0_321]
	at java.nio.charset.Charset.forName(Unknown Source) ~[?:1.8.0_321]
	at com.pega.gcs.fringecommon.guiutilities.RecentFile.getCharset(RecentFile.java:95) ~[fringeutils-common-v3.4.1.jar:3.5.0-dev.0.uncommitted+0d3cd02]
	at com.pega.gcs.fringecommon.guiutilities.FilterTableModel.getCharset(FilterTableModel.java:145) ~[fringeutils-common-v3.4.1.jar:3.5.0-dev.0.uncommitted+0d3cd02]
	at com.pega.gcs.tracerviewer.TracerFileLoadTask.doInBackground(TracerFileLoadTask.java:100) ~[pega-tracerviewer-3.4.1.jar:3.4.1]
	at com.pega.gcs.tracerviewer.TracerFileLoadTask.doInBackground(TracerFileLoadTask.java:45) ~[pega-tracerviewer-3.4.1.jar:3.4.1]
	at javax.swing.SwingWorker$1.call(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
	at javax.swing.SwingWorker.run(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_321]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_321]

**Comment by vargm** [comment]
Hello @dvmierlo ,
Can you please refer to the [README](https://github.com/pegasystems/pega-tracerviewer#readme) and follow the steps on the Known Issues section.

- Reset Tool settings
	- Edit -> Settings
	- Click Reset then OK.
- Clear Recent files
	- File -> Clear Recent
	
Thanks

**Comment by lewisandrew** [comment]
I also got the same issue, and those steps in the README didn't help

**Comment by lewisandrew** [comment]
The issue also occurs on 3.4.0, but not on 3.3.0
